name: Convert HTML to Data URL

on: [push]

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install fs

    - name: Convert HTML to Data URL
      run: |
        const fs = require('fs');
        const file = fs.readFileSync('./eded.html', 'utf8');
        const base64 = Buffer.from(file).toString('base64');
        const dataUrl = `data:text/html;base64,${base64}`;
        console.log(dataUrl);
      shell: node